<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BusinessBackground;

class BusinessBackgroundSeeder extends Seeder
{
    public function run(): void
    {
        BusinessBackground::create([
            'user_id' => 1,
            'logo' => null, // Bisa diisi dengan path gambar: 'uploads/logo.png'
            'name' => 'Kedai Kopi Pandu',
            'category' => 'Kuliner',

            // Deskripsi singkat untuk header
            'description' => 'Kedai kopi premium dengan suasana cozy untuk komunitas mahasiswa dan profesional muda di Jember. Kami menyajikan kopi specialty berkualitas tinggi dengan harga terjangkau dan layanan terbaik. Dilengkapi dengan WiFi super cepat, ruang meeting nyaman, dan berbagai pilihan makanan sehat untuk menemani aktivitas harian Anda.',

            // Overview bisnis yang detail dan lengkap
            'business_overview' => 'Kedai Kopi Pandu merupakan coffee shop yang didirikan pada Juni 2023 dengan fokus utama melayani komunitas mahasiswa Universitas Jember dan profesional muda di area Jember. Dengan konsep "Third Place" - tempat ketiga setelah rumah dan kantor/kampus - kami menciptakan atmosfer yang mendukung produktivitas, kreativitas, dan interaksi sosial yang bermakna.\n\nKami mengusung konsep specialty coffee dengan menggunakan 100% biji kopi Arabica pilihan dari petani lokal Jawa Timur, khususnya dari perkebunan Ijen dan Bondowoso. Setiap biji kopi dipilih dengan cermat, disangrai fresh setiap minggu dengan profil medium roast untuk menghasilkan rasa yang balance antara acidity, sweetness, dan body.\n\nSelain kopi berkualitas, kami juga menyediakan berbagai pilihan non-coffee beverages seperti matcha latte premium, chocolate drinks, dan fresh juice. Menu makanan kami mencakup berbagai pilihan healthy meals, pastries homemade, dan snacks yang perfect untuk menemani aktivitas belajar atau meeting.\n\nFasilitas yang kami tawarkan meliputi: WiFi super cepat 100 Mbps, power outlet di setiap meja, AC full, ruang meeting untuk 6-8 orang, outdoor seating area, dan private booth untuk diskusi kelompok. Kami juga menyediakan board games gratis dan mini library untuk menambah kenyamanan pengunjung.\n\nTarget market kami sangat spesifik: mahasiswa aktif (70%), profesional muda dan startup founders (20%), serta komunitas dan freelancer (10%). Dengan positioning ini, kami berhasil menciptakan loyal customer base yang kuat dengan repeat visit rate mencapai 65% per bulan.',

            // Legalitas bisnis yang lengkap
            'business_legality' => 'Kedai Kopi Pandu telah memiliki legalitas usaha yang lengkap dan sesuai dengan regulasi pemerintah Indonesia. Berikut adalah dokumen legal yang kami miliki:\n\n1. NIB (Nomor Induk Berusaha): 1234567890123 - terdaftar di OSS (Online Single Submission) sejak Juli 2023\n\n2. NPWP Badan Usaha: 12.345.678.9-012.000 - untuk keperluan perpajakan dan pelaporan keuangan\n\n3. Izin Usaha Mikro Kecil (IUMK) dari Dinas Perindustrian dan Perdagangan Kabupaten Jember\n\n4. Sertifikat Halal dari MUI Jawa Timur No. 00112233445566 - berlaku hingga 2026, mencakup seluruh produk makanan dan minuman yang kami sajikan\n\n5. Izin Edar PIRT (Pangan Industri Rumah Tangga) No. 2157890123456789 untuk produk pastries dan makanan homemade\n\n6. Tanda Daftar Usaha Pariwisata (TDUP) untuk kategori restoran/kafe\n\n7. Perjanjian sewa lokasi dengan masa kontrak 5 tahun (2023-2028) yang telah dinotariskan\n\n8. Izin Gangguan (HO) dari pemerintah setempat\n\n9. Asuransi properti dan liability dari PT Asuransi XYZ dengan coverage hingga 500 juta rupiah\n\nSemua dokumen legal diperbaharui secara berkala dan kami memastikan kepatuhan penuh terhadap regulasi kesehatan, keamanan pangan, dan standar operasional yang berlaku.',

            // Tujuan bisnis yang detail dan terukur
            'purpose' => 'Menyediakan tempat nongkrong yang nyaman, berkualitas, dan terjangkau khususnya untuk mahasiswa UNEJ dan area sekitarnya. Kami berkomitmen menciptakan ruang yang inspiratif untuk belajar, bertemu, dan berkolaborasi sambil menikmati kopi terbaik.\n\nTujuan spesifik kami adalah:\n1. Menjadi daily destination bagi minimal 150 pelanggan per hari di tahun pertama operasional\n2. Mencapai customer satisfaction score minimal 4.5/5.0 berdasarkan review online\n3. Membangun komunitas loyal dengan membership program yang mencapai 500 anggota aktif\n4. Mendukung petani kopi lokal dengan membeli minimal 500kg biji kopi per bulan dari koperasi petani setempat\n5. Menciptakan 15 lapangan kerja untuk pemuda lokal dengan pelatihan barista profesional\n6. Break even point dalam 18 bulan pertama dan profit margin 25% di tahun kedua',

            // Objektif bisnis yang terstruktur
            'business_objectives' => 'OBJEKTIF JANGKA PENDEK (Tahun 1-2):\n\n1. Pertumbuhan Revenue:\n   - Mencapai omzet Rp 150 juta per bulan di tahun pertama\n   - Meningkat menjadi Rp 200 juta per bulan di tahun kedua\n   - Gross profit margin minimal 60%\n\n2. Customer Acquisition:\n   - Mendapatkan 3000 unique customers dalam 12 bulan pertama\n   - Average transaction value Rp 45.000 per customer\n   - Customer retention rate minimal 40%\n\n3. Operational Excellence:\n   - Service time maksimal 5 menit per order\n   - Product consistency score 95%\n   - Zero food safety incidents\n\n4. Brand Building:\n   - Instagram followers mencapai 10.000 dalam tahun pertama\n   - Engagement rate minimal 5%\n   - Featured di minimal 3 media lokal\n\nOBJEKTIF JANGKA MENENGAH (Tahun 3-4):\n\n1. Ekspansi Bisnis:\n   - Membuka cabang kedua di area kampus yang berbeda\n   - Meluncurkan delivery service dan online ordering system\n   - Mengembangkan product line berupa packaged coffee beans untuk retail\n\n2. Market Leadership:\n   - Menjadi Top 3 coffee shop pilihan mahasiswa di Jember\n   - Market share 15% di segmen specialty coffee\n   - Brand awareness 60% di target demographic\n\n3. Sustainability:\n   - Implementing zero waste policy dengan 80% waste reduction\n   - Partnership dengan 5 farmer cooperatives\n   - Solar panel installation untuk 30% energy needs\n\nOBJEKTIF JANGKA PANJANG (Tahun 5+):\n\n1. Regional Expansion:\n   - 5 outlets di kota-kota berbeda di Jawa Timur\n   - Franchise opportunity untuk entrepreneur lokal\n   - Central kitchen untuk supply chain efficiency\n\n2. Diversifikasi Bisnis:\n   - Coffee academy untuk training barista\n   - Roastery sendiri untuk kontrol kualitas penuh\n   - E-commerce platform untuk coffee beans dan merchandise',

            'location' => 'Ruko Kampus, Jalan Kalimantan No. 45, Tegalboto, Jember, Jawa Timur 68121 (50 meter dari gerbang utama Universitas Jember)',
            'business_type' => 'UMKM (Usaha Mikro Kecil Menengah) - Perseroan Terbatas (PT)',
            'start_date' => '2023-06-01',

            // Nilai-nilai bisnis yang komprehensif dan bermakna
            'values' => 'CORE VALUES Kedai Kopi Pandu:\n\n1. QUALITY FIRST - Tidak pernah berkompromi dengan kualitas. Dari pemilihan biji kopi, proses penyeduhan, hingga presentation, semuanya harus excellence. Kami percaya bahwa kualitas adalah investasi jangka panjang untuk kepercayaan pelanggan.\n\n2. CUSTOMER CENTRICITY - Setiap keputusan bisnis kami dimulai dengan pertanyaan: "Apa yang terbaik untuk customer kami?" Kami mendengarkan feedback, beradaptasi dengan kebutuhan, dan selalu berusaha exceed expectations.\n\n3. SUSTAINABILITY & SOCIAL RESPONSIBILITY - Kami berkomitmen pada praktik bisnis yang sustainable. Dari sourcing biji kopi yang fair trade, menggunakan packaging ramah lingkungan, hingga program community development untuk petani kopi lokal.\n\n4. INTEGRITY & TRANSPARENCY - Kejujuran adalah fondasi bisnis kami. Kami transparan dalam pricing, jujur tentang produk kami, dan fair dalam semua partnership. No hidden costs, no false promises.\n\n5. INNOVATION & CONTINUOUS IMPROVEMENT - Industri F&B terus berkembang, dan kami harus selalu berinovasi. Dari menu development, service improvement, hingga technology adoption - kami embrace perubahan positif.\n\n6. PEOPLE DEVELOPMENT - Team kami adalah asset terbesar. Kami invest dalam training, menciptakan career path yang jelas, dan membangun work culture yang supportive dan inclusive.\n\n7. COMMUNITY BUILDING - Lebih dari sekadar coffee shop, kami adalah community hub. Kami facilitate connections, support local talents, dan create space untuk meaningful interactions.',

            // Visi yang inspiratif, specific, dan achievable
            'vision' => 'Menjadi coffee shop pilihan utama dan "Third Place" terfavorit bagi mahasiswa dan young professionals di Jember pada tahun 2025, dengan reputasi sebagai tempat yang menyajikan specialty coffee terbaik, atmosfer paling kondusif untuk produktivitas, dan komunitas paling supportive.\n\nPada tahun 2027, kami ingin menjadi regional chain dengan 5 outlets di kota-kota pendidikan di Jawa Timur (Malang, Surabaya, Kediri, Madiun) dan dikenal sebagai brand yang champion sustainability, quality, dan community empowerment.\n\nVisi jangka panjang kami adalah menjadi social enterprise yang tidak hanya profitable, tetapi juga memberikan positive impact kepada ecosystem kopi Indonesia - dari petani hingga consumer - melalui fair trade practices, quality education, dan community development programs.',

            // Misi yang detail, actionable, dan measurable
            'mission' => 'MISI OPERASIONAL:\n\n1. PRODUCT EXCELLENCE\n   - Menyajikan specialty coffee dengan consistency score 95%+\n   - Menggunakan 100% biji kopi Arabica dari petani lokal dengan fair trade pricing\n   - Refresh menu setiap quarter dengan minimal 2 new signature drinks\n   - Maintain freshness dengan roasting cycle maksimal 2 minggu\n\n2. SERVICE EXCELLENCE\n   - Memberikan warm greeting dan genuine smile kepada setiap customer\n   - Response time maksimal 3 menit untuk order taking\n   - Serving time maksimal 5 menit untuk standard drinks\n   - Handle complaints dengan 24-hour resolution guarantee\n   - Training staff secara regular untuk product knowledge dan soft skills\n\n3. SPACE & ATMOSPHERE\n   - Menciptakan "Third Place" yang comfortable untuk work, study, atau socialize\n   - Maintain cleanliness dengan hourly cleaning protocol\n   - Provide reliable WiFi (99% uptime) dan sufficient power outlets\n   - Curate playlist dan lighting yang conducive untuk berbagai activities\n   - Temperature control untuk comfort level optimal\n\n4. COMMUNITY BUILDING\n   - Host minimal 2 community events per bulan (open mic, book club, workshop)\n   - Partnership dengan student organizations untuk co-create value\n   - Support local artists dengan exhibition space dan commission-free sales\n   - Loyalty program yang rewarding untuk regular customers\n\n5. SUSTAINABILITY COMMITMENT\n   - Zero single-use plastic pada 2025\n   - Waste reduction minimal 80% melalui composting dan recycling\n   - Energy efficiency dengan renewable energy usage\n   - Water conservation dengan filtration system\n\n6. SOCIAL IMPACT\n   - Fair pricing untuk farmers dengan direct trade partnership\n   - Employment untuk local youth dengan competitive wage dan benefits\n   - Scholarship program untuk barista training\n   - Donate 2% dari profit untuk community development programs',

            'contact' => 'Instagram: @kedaikopipandu | WA: +62 821-3456-7890 | Email: hello@kedaikopipandu.com',
        ]);
    }
}
